### ISSUE TITLE
Slash commands not registering properly/taking too long

### ISSUE THREAD

**Issue by stoir** [CSC510-G35-Fall2022/Mental_Health#26]

**Comment by stoir** [comment]
Slash commands were not registering properly. There is also a bug because none of the commands are getting registerd.

**Comment by stoir** [comment]
Fixed the bug, the commands were getting initialized globally (can take hours sometimes). changed this to be initialized locally per guild (updates instantly).  The code had a bug where the async command registration was not updating, moved and edited the code to resolve it.

Resolved bug. Requesting pull request.

**Comment by Culcheese** [comment]
Fixed with pull request merge
