### ISSUE TITLE
Roadmap for future updates

### ISSUE THREAD

**Issue by Culcheese** [CSC510-G35-Fall2022/Mental_Health#8]
Leave a roadmap of issues or things to work on for future projects
Example: https://github.com/se20z09/units_converter_extension/projects/1

**Comment by maya-dc-patel** [comment]
<img width="383" alt="Screen Shot 2022-10-02 at 11 13 52 PM" src="https://user-images.githubusercontent.com/79175476/193495290-047abadc-2d53-403f-8e51-3572129a0ca4.png">
Would a roadmap like this be too simple??

**Comment by stoir** [comment]
Created under projects
